apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  creationTimestamp: null
  name: default-git-source-sensor
  namespace: codefresh
spec:
  dependencies:
  - eventName: workflowTemplate
    eventSourceName: default-git-source-event-source
    name: workflowTemplate
  - eventName: workflow
    eventSourceName: default-git-source-event-source
    name: workflow
  - eventName: appProject
    eventSourceName: default-git-source-event-source
    name: appProject
  - eventName: application
    eventSourceName: default-git-source-event-source
    name: application
  - eventName: eventBus
    eventSourceName: default-git-source-event-source
    name: eventBus
  - eventName: eventSource
    eventSourceName: default-git-source-event-source
    name: eventSource
  - eventName: sensor
    eventSourceName: default-git-source-event-source
    name: sensor
  - eventName: rollout
    eventSourceName: default-git-source-event-source
    name: rollout
  eventBusName: codefresh-eventbus
  triggers:
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: workflowTemplate
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: workflowTemplate
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: workflow
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: workflow
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: appProject
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: appProject
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: application
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: application
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: eventBus
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: eventBus
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: eventSource
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: eventSource
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: sensor
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: sensor
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: rollout
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data
          src:
            dataKey: body
            dependencyName: rollout
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://g.codefresh.io/argo/api/events
      name: http-trigger
status: {}
