apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: events-reporter
  namespace: noam-8
spec:
  eventBusName: codefresh-eventbus
  generic:
    events:
      authSecret:
        key: token
        name: argocd-token
      config: '{}'
      insecure: true
      url: argocd-server.noam-8.svc:80
  template: {}
status: {}
