apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cli-v2
  name: events-reporter
  namespace: noam-1
spec:
  eventBusName: codefresh-eventbus
  generic:
    events:
      authSecret:
        key: token
        name: argocd-token
      config: '{}'
      insecure: true
      url: argocd-server.noam-1.svc:80
  template: {}
status: {}
