apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: workflow-reporter
  namespace: noam-9
spec:
  eventBusName: codefresh-eventbus
  resource:
    workflows:
      eventTypes:
      - ADD
      - UPDATE
      - DELETE
      filter:
        createdBy: null
      group: argoproj.io
      namespace: noam-9
      resource: workflows
      version: v1alpha1
  template:
    serviceAccountName: codefresh-sa
status: {}
